// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from '@prisma/config';
import path from 'path';

export default defineConfig({
  datasource: {
    url: `file:${path.join(import.meta.dirname, 'dev.db')}`,
  },
});
